### PR TITLE
Updated CloudWatchAgentUrl example

### PR DESCRIPTION
**Pull request by nortiz34**

### CODE REVIEW

**Comment by userhas404d** [comment]
Can you update the win-autoscale module too, please?

**Comment by moskey71** [comment]
I think what's going on is there are two PRs.  @nortiz34  can you put all the changes you want to make into one branch/PR so we can review them all at once?

**Comment by lorengordon** [comment]
I think we can review and merge two separate prs, each with a change to two different files.

**Comment by moskey71** [comment]
Seems to me that if the same change to multiple templates, it might as well be in one PR  for brevity.

**Comment by lorengordon** [comment]
When editing a file via the GitHub UI, that is not really offered as an option, and that is a workflow we can encourage for such simple changes (we certainly do not want to discourage contributions).

**Comment by moskey71** [comment]
Ah, this was done through the UI.  In that case, I think it can be done by creating a branch, then making multiple commits(edits) to it, and then submitting the PR.  Just tested it and it seems to work: https://github.com/plus3it/terraform-aws-watchmaker/pull/146

**Comment by lorengordon** [comment]
So, need a fork, need a branch, need to edit and commit multiple files, then open a pr from a branch?

Vs the built-in workflow for editing a file, which automatically forks, branches, and walks you through the commit and pr. We're definitely supporting this simpler workflow, especially for simple edits that do not impact code.

**Pull request merged**
