### PR TITLE
Update CFN template from LaunchConfig to LaunchTemplate.

### PR DESCRIPTION
**Pull request by kumoy**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
@kumoy Please fix the test config, and `bumpversion minor`. Then we can get this merged.

**Comment by kumoy** [comment]
go codebuild go

**Comment by kumoy** [comment]
go codebuild go

**Comment by kumoy** [comment]
go codebuild go

**Comment by kumoy** [comment]
go codebuild go

**Comment by kumoy** [comment]
go codebuild go

**Comment by kumoy** [comment]
go codebuild go

**Review by lorengordon — APPROVED** [review]

**Pull request merged**
